### ISSUE TITLE
Jumping after mounting happens too soon

### ISSUE THREAD

**Issue by Noshei** [awgil/ffxiv_visland#6] opened 2023-08-17 19:18 UTC
the first jump after mounting happens too soon and results in a jump happening before your character is mounted.  I suspect this is a result of the queuing system.

**Comment by awgil** [comment] 2023-09-01 22:14
Should be fixed in the new version - I've reworked the way I do movement. Please reopen with more details if it turns out to be still reproducible.

**Closed by awgil** 2023-09-01 22:14 UTC
