### ISSUE TITLE
Mounting fails because jumping

### ISSUE THREAD

**Issue by LalaGobbie** [awgil/ffxiv_visland#9] opened 2023-08-26 11:00 UTC
The "Mount" function does not work for me because 90% of the time the character will jump before becoming mounted. 

The character will try to mount a few times before giving up and running to the next waypoint.

**Comment by awgil** [comment] 2023-09-01 22:14
Should be fixed in the new version - I've reworked the way I do movement. Please reopen with more details if it turns out to be still reproducible.

**Closed by awgil** 2023-09-01 22:14 UTC
