### ISSUE TITLE
vertical only movement while mounted is very buggy

### ISSUE THREAD

**Issue by Noshei** [awgil/ffxiv_visland#8] opened 2023-08-17 21:06 UTC
if you need to only move vertically while mounted, the movement is very buggy and slow.

**Comment by awgil** [comment] 2023-09-01 22:14
Should be fixed in the new version - I've reworked the way I do movement. Please reopen with more details if it turns out to be still reproducible.

**Closed by awgil** 2023-09-01 22:14 UTC
